### ISSUE TITLE
Port to cmake

### ISSUE THREAD

**Issue by nyalldawson** [evanmiller/mdbtools#20]
Autotools is doing my head in :stuck_out_tongue_winking_eye:

**Comment by evanmiller** [comment]
I'm open to it, but porting might be more trouble than it's worth. (I also maintain a few other projects with Autotools, so in spite of all its flaws and shortcomings Autotools is the most comfortable environment for me.)

Is there anything in particular you're trying to achieve?

**Comment by nyalldawson** [comment]
I was trying to get an asan enabled build setup for a potential addition to the travis testing. It's straightforward in cmake, but can't work out the magic commands needed to get this working in autotools...

**Comment by evanmiller** [comment]
FYI I have some ASAN stuff enabled in my fuzz-testing branch

https://github.com/evanmiller/mdbtools/tree/fuzz-testing

**Comment by nyalldawson** [comment]
OK, I'll see if I can adapt that...

**Comment by evanmiller** [comment]
I'm shutting down the issue tracker on my personal fork, so please open new issues on the official repo
