### ISSUE TITLE
ODBC Driver is not thread safe

### ISSUE THREAD

**Issue by evanmiller** [evanmiller/mdbtools#23]
There is global shared state in both `odbc.c` (e.g. the iconv objects) and also `connectparams.c`.

**Comment by evanmiller** [comment]
@nyalldawson Is the following still true after #16?

https://github.com/evanmiller/mdbtools/blob/1ad0dd2d8b9ef7b6e70c4f13ccdad901a13763fa/src/odbc/odbc.c#L166-L168

**Comment by nyalldawson** [comment]
That comment can be removed -- while it's always possible I missed something, I'm confident it's safe now!

**Comment by evanmiller** [comment]
Ok, consider it gone!
