### ISSUE TITLE
Revisit "no release" decision?

### ISSUE THREAD

**Issue by nyalldawson** [evanmiller/mdbtools#25]
In the readme docs you state:

> I am not planning a formal release but rather collecting and merging patches to submit upstream

Is this a hardline decision? It's quite evident that upstream is about as dead as it gets, and an upstream PR will get no attention. (In fact, the original maintainer hasn't had any github activity since May 2017, regardless of the project.)

This fork has so many important fixes, from data corruption to crash fixes and the like, that I think it's important that we get this fork pushed into as many downstream linux distributions and other packaging environments as possible. (There's already a debian ticket regarding this here: https://bugs.debian.org/968384 ). Implementing formal releases and removing that wording from the readme would assist with these efforts and add confidence that this is the "new upstream".

**Comment by evanmiller** [comment]
My ordered preferences are:

1. Get changes committed upstream (not likely)

2. Get commit / admin access to upstream (maybe more likely?)

3. Do a hard fork with a new name

I think it will create headaches if we fork but keep the MDBTools name and provide the same system files. A hard fork will be easier for people (including package maintainers) to understand.

**Comment by nyalldawson** [comment]
> Get commit / admin access to upstream (maybe more likely?)

I've looked into this, but unless an existing admin gives you access, github themselves **don't** offer any way to take over someone else's repo.

Maybe hard fork (with a API compatible pledge?) is the way to go...

**Comment by evanmiller** [comment]
I already maintain [libxls](https://github.com/libxls) so I'd be inclined to have a single GitHub organization manage both projects. (For all your 90s binary Microsoft file format reading needs.)

We could keep the API the same (for now), but we'd need to rename the tools and libraries to accommodate side-by-side installations.

**Comment by nyalldawson** [comment]
That works for me!

**Comment by evanmiller** [comment]
👋 @nirgal Any chance of MDB Tools getting some attention? We have a ton of patches in this branch and would prefer merging over forking. I'm more than willing to help with maintenance.

**Comment by nyalldawson** [comment]
If we're going for a new project approach, I suggest we use the opportunity to drop the old gtk UI code entirely from this project and instead leave it as a library only...

**Comment by evanmiller** [comment]
@nyalldawson I have the keys to the kingdom now, so yes - there will be an official release.

You're welcome to open PRs here until our work is merged upstream.
