### ISSUE TITLE
Run clang-format over source

### ISSUE THREAD

**Issue by nyalldawson** [evanmiller/mdbtools#27]
The source is an inconsistent mix of tabs/spaces/bracing styles. We should consider running clang-format over it and settling for a standard formatting style for new submissions

**Comment by evanmiller** [comment]
I'm not keen to trash the `git blame`, is there any way to sneak in a re-format?

**Comment by evanmiller** [comment]
Closing up shop here - Feel free to open a similar issue on the official repo.
