### ISSUE TITLE
odbc driver returns datetime values in incorrect format

### ISSUE THREAD

**Issue by nyalldawson** [evanmiller/mdbtools#28]
The odbc driver should  be returning datetime values in a `yyyy-mm-dd[ hh:mm:ss[.9999999][ plus/minus hh:mm]]` format (see https://docs.microsoft.com/en-us/sql/relational-databases/native-client-odbc-date-time/datetime-data-type-conversions-odbc?view=sql-server-ver15), but instead is using the access style 'mm-dd-yy hh:mm' format.

**Comment by evanmiller** [comment]
For ODBC < 3 the driver is just copying out the text that libmdb hands it, i.e.

https://github.com/evanmiller/mdbtools/blob/2887fa49edf803ba37cffc7d21127be9b5b0b303/src/libmdb/data.c#L40

But this can be customized (in a horrible non-thread-safe way) using

https://github.com/evanmiller/mdbtools/blob/2887fa49edf803ba37cffc7d21127be9b5b0b303/src/libmdb/data.c#L45-L49

**Comment by nyalldawson** [comment]
Actually it's also used for ODBC >= 3 if SQLFetch is called. 

I was pondering adding a "date format" field to MdbTableDef which would then be passed to _mdb_attempt_bind and finally mdb_xfer_bound_data. Then mdb_xfer_bound_data would call mdb_date_to_string directly for date time columns instead of going through mdb_col_to_string. And mdb_date_to_string could accept a new "format" argument for explicitly specifying the output format...

**Comment by evanmiller** [comment]
I don't have a strong opinion, feel free to take a crack at it. `mdb_set_date_fmt` should probably operate on an MdbHandle, at least. I'll mess around with that end of things.
