### ISSUE TITLE
Resurrect and fix SQLGetData fix

### ISSUE THREAD

**Issue by nyalldawson** [evanmiller/mdbtools#6]
https://github.com/brianb/mdbtools/pull/131 describes a real bug in SQLGetData, however the included fix isn't quite right (it results in missing data from some rows). We should resurrect and complete this fix...

**Comment by evanmiller** [comment]
Do you have a test case?

**Comment by nyalldawson** [comment]
[Atlanticx.zip](https://github.com/evanmiller/mdbtools/files/5048826/Atlanticx.zip)

here's an example (Routes_Master) table:

Sizes reported by Access:

```
OBJECTID Expr1
1 656
2 212
3 1688
4 368
5 656
6 4280
```

Sizes reported by mdb_ole_read_full:

```
1: 1312
2: 424
3: 3376
4: 736
5: 1312
6: 8560
```

Sizes reported by SQLGetData

```
1: 1314
2: 424
3: 3382
4: 737
5: 1314
6: 8576
```

**Comment by nyalldawson** [comment]
(I'm not sure why access is reporting 2x the field size! :laughing: )

**Comment by evanmiller** [comment]
Thanks, I'll take a look later this week. The size-doubling was also reported here:

https://github.com/brianb/mdbtools/issues/112

**Comment by evanmiller** [comment]
Which ODBC library / version are you using?

**Comment by nyalldawson** [comment]
unixODBC v 2.3.7

**Comment by evanmiller** [comment]
Thanks. Can you please provide a test program that demonstrates the GetData bug? (The incorrect field sizes might be a separate bug.)

**Comment by evanmiller** [comment]
Please try #8

**Comment by nyalldawson** [comment]
Unfortunately I'm unable to test anything past abe7ebcb74 -- the subsequent commits cause a deadlock in the unixodbc code for some reason :thinking:

**Comment by nyalldawson** [comment]
Let me test with just a cherry-pick -- it applies cleanly

**Comment by evanmiller** [comment]
> Unfortunately I'm unable to test anything past [abe7ebc](https://github.com/evanmiller/mdbtools/commit/abe7ebcb74f0a5126aa43b67300f6faeb16ae978) -- the subsequent commits cause a deadlock in the unixodbc code for some reason 🤔

I've been using iODBC for all my testing. I'll install unixODBC and try to reproduce the deadlock.
